apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-form-service
  labels:
    app: circleguard-form-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-form-service
  template:
    metadata:
      labels:
        app: circleguard-form-service
    spec:
      containers:
        - name: circleguard-form-service
          image: circleguard-form-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/circleguard_form"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
              value: "org.apache.kafka.common.serialization.StringSerializer"
            - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
              value: "org.springframework.kafka.support.serializer.JsonSerializer"
---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-form-service
spec:
  type: NodePort
  selector:
    app: circleguard-form-service
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086
